name: foody
description: "food delivery app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ^3.6.0-55.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dots_indicator: ^3.0.0
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  flutter_typeahead: ^5.2.0
  google_maps_flutter_web: ^0.5.10
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  webview_flutter: ^4.8.0
  uuid: ^4.5.1
  lottie: ^3.1.3
  # flutter_google_places: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/icon/icon.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900