import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmTEYSiN7xCgepz3nHj6xpSy_ejBBp3TQ',
    appId: '1:329206191684:web:1aeb67c55d88476bbd4e11',
    messagingSenderId: '329206191684',
    projectId: 'food-delivery-2c093',
    authDomain: 'food-delivery-2c093.firebaseapp.com',
    storageBucket: 'food-delivery-2c093.firebasestorage.app',
    measurementId: 'G-SKHM1BDVBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZr6VJ2xHbVyPIF0uBGqWRResyrCxo60',
    appId: '1:329206191684:android:04e1c75c7c1c6fd6bd4e11',
    messagingSenderId: '329206191684',
    projectId: 'food-delivery-2c093',
    storageBucket: 'food-delivery-2c093.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZJOPpc5mQ20h1K1XBOl66djZeKVTXOE',
    appId: '1:329206191684:ios:9f990e3745f7afd7bd4e11',
    messagingSenderId: '329206191684',
    projectId: 'food-delivery-2c093',
    storageBucket: 'food-delivery-2c093.firebasestorage.app',
    iosBundleId: 'com.hninhninwai.xyz.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEZJOPpc5mQ20h1K1XBOl66djZeKVTXOE',
    appId: '1:329206191684:ios:9f990e3745f7afd7bd4e11',
    messagingSenderId: '329206191684',
    projectId: 'food-delivery-2c093',
    storageBucket: 'food-delivery-2c093.firebasestorage.app',
    iosBundleId: 'com.hninhninwai.xyz.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmTEYSiN7xCgepz3nHj6xpSy_ejBBp3TQ',
    appId: '1:329206191684:web:bf5bf93f7e3a6667bd4e11',
    messagingSenderId: '329206191684',
    projectId: 'food-delivery-2c093',
    authDomain: 'food-delivery-2c093.firebaseapp.com',
    storageBucket: 'food-delivery-2c093.firebasestorage.app',
    measurementId: 'G-T8P3QZKT8L',
  );
}
